"""inital schema

Revision ID: 88bc5af553e9
Revises: 
Create Date: 2026-05-01 14:05:51.207085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bc5af553e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('dining_halls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('short_key', sa.String(length=100), nullable=False),
    sa.Column('hall_slug', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'short_key', name='uq_hall_school_key')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('serving_size', sa.String(length=100), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein', sa.Integer(), nullable=True),
    sa.Column('carbs', sa.Integer(), nullable=True),
    sa.Column('fats', sa.Integer(), nullable=True),
    sa.Column('sugar', sa.Integer(), nullable=True),
    sa.Column('protein_per_calorie', sa.Float(), nullable=True),
    sa.Column('calories_per_protein', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['hall_id'], ['dining_halls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hall_id', 'meal_type', 'date', 'name', name='uq_menu_item')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_items')
    op.drop_table('dining_halls')
    op.drop_table('schools')
    # ### end Alembic commands ###
